### ISSUE TITLE
Can we apply the optimized VarSort5 to the LLVM C++ standard library

### ISSUE THREAD

**Issue by laoshucike** [deepmind/alphadev#4]
Following the same idea of adding sort3, sort4, and sort5 to the LLVM C++ standard library, is it possible to reverse engineer the VarSort5 assembly code and use it in the LLVM C++ standard library?

Notice that in the current LLVM C++ sort implementation, a function similar to VarSort5 is used: https://github.com/llvm/llvm-project/blob/main/libcxx/include/__algorithm/sort.h#L711-L730. 

I'm not sure how much performance gain it would get, and whether the maintainer likes the idea. Based on the paper, the VarSort5 reduces latency by around 6% compared to the human benchmark.

Looking for comments. Thanks!

**Comment by ohhmm** [comment]
It may conjunct with merge-sort well btw. Need to measure performance.

**Comment by andydude** [comment]
You should also measure correctness.

**Comment by ohhmm** [comment]
@andydude, merge sort by default definition sorts by two items first. Then merges sorted sequence of two elements to four. Then it merges sorted sequences of four elements to eight. And so on.

With this implementation the merge sorting may start from optimized sorting of five elements. Then it can merge sorted sequences of five elements to ten-element sequences in parallel using OpenCL.

I hope this measures correctness for you.
